name: Generate Kaggle Profile Card

on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Kaggle Username'
        required: true
        default: 'your-kaggle-username'

jobs:
  generate-profile-card:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run --name kaggle-profile-card-generator \
        -v "${{ github.workspace }}/output:/app/output" \
        victoriosus/kaggle-badge:v5.0 \
        python script.py ${{ github.event.inputs.username }}

    # Nuevo paso para copiar el archivo generado al directorio de trabajo
    - name: Copy Kaggle Card to Workspace
      run: cp output/Kaggle_card.png ${{ github.workspace }}

    # Nuevo paso para configurar el usuario de git. Reemplaza con tu nombre y correo
    - name: Configure Git
      run: |
        git config user.name "example"
        git config user.email "githubactions@example.com"

    # Nuevo paso para cometer y empujar el archivo al repositorio
    - name: Commit and Push Kaggle Card to Repository
      run: |
        git add ${{ github.workspace }}/Kaggle_card.png
        git commit -m "Add Kaggle Profile Card for ${{ github.event.inputs.username }}"
        git push
