name: Generate Kaggle Profile Card

on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Kaggle Username'
        required: true
        default: 'your-kaggle-username'

jobs:
  generate-profile-card:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run --name kaggle-profile-card-generator \
        victoriosus/kaggle-badge:v5.0 \
        python script.py ${{ github.event.inputs.username }}
