name: Generate Kaggle Profile Card

on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Kaggle Username'
        required: true
        default: 'your-kaggle-username'

jobs:
  generate-profile-card:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run --name kaggle-profile-card-generator \
        victoriosus/kaggle-badge:v5.0 \
        python script.py ${{ github.event.inputs.username }}
        docker exec kaggle-profile-card-generator ls -l
        docker cp kaggle-profile-card-generator:/Kaggle_card.png .

    - name: Commit and Push Kaggle Card to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Kaggle-badge.png
        git commit -m "Add Kaggle Profile Card"
        git push
